#!/usr/bin/env python3
"""Generate the devnet-only devseed realm from the import batches.

    tools/dev/seedgen.py [batch.json ...]   default: tools/curate/import_batch.json,
                                             plus tools/curate/pointers_batch.json if present

The lines are encoded by tools/deploy/import.py's batch_arg, the same encoder the real
import uses; only the artist id is a placeholder ("@<index>") resolved on chain.
"""
import json
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
sys.path.insert(0, os.path.join(ROOT, "tools", "deploy"))
import importlib.util  # noqa: E402

spec = importlib.util.spec_from_file_location("imp", os.path.join(ROOT, "tools", "deploy", "import.py"))
imp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(imp)


def gostr(s):
    return json.dumps(s, ensure_ascii=False)  # a JSON string is a valid Go string literal


def main(paths):
    if not paths:
        paths = [os.path.join(ROOT, "tools", "curate", "import_batch.json")]
        p = os.path.join(ROOT, "tools", "curate", "pointers_batch.json")
        if os.path.exists(p):
            paths.append(p)
    artists, index, tracks = [], {}, []
    for p in paths:
        b = json.load(open(p))
        for a in b["artists"]:
            if a["key"] not in index:
                index[a["key"]] = "@%d" % len(artists)
                artists.append("\t".join((a["kind"], a["name"], a["source_url"])))
        tracks += b["tracks"]
    batches = [imp.batch_arg(tracks[i:i + imp.BATCH], index) for i in range(0, len(tracks), imp.BATCH)]
    out = os.path.join(ROOT, "gno", "r", "gnoradio", "devseed", "v0")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "seed.gno"), "w") as f:
        f.write(open(os.path.join(ROOT, "tools", "dev", "devseed.gno.tmpl")).read())
    with open(os.path.join(out, "data.gno"), "w") as f:
        f.write("// Code generated by tools/dev/seedgen.py. DO NOT EDIT.\n\npackage devseed\n\n")
        f.write("var artists = []string{\n" + "".join("\t%s,\n" % gostr(a) for a in artists) + "}\n\n")
        f.write("var batches = []string{\n" + "".join("\t%s,\n" % gostr(b) for b in batches) + "}\n")
    with open(os.path.join(out, "gnomod.toml"), "w") as f:
        f.write('module = "gno.land/r/gnoradio/devseed/v0"\ngno = "0.9"\n')
    print("devseed: %d artists, %d tracks in %d batches" % (len(artists), len(tracks), len(batches)))


if __name__ == "__main__":
    main(sys.argv[1:])
