#!/bin/sh
# Start the GnoRadio local devnet: gnodev on 127.0.0.1:27157 (RPC) and :8911 (gnoweb),
# chain id "dev", with the onyx-matched toolchain. Run from anywhere; it stops a previous
# devnet on 27157 first (and only that one). Then seed it: tools/dev/README.md.
set -eu
cd "$(dirname "$0")/../.."
TC=${GNO_TOOLCHAIN:-$HOME/.cache/gno-toolchains/onyx-v1.5.0}
export GNOROOT=${GNOROOT:-$HOME/go/pkg/mod/github.com/gnolang/gno@v1.5.0}
export GNOHOME=${GNOHOME:-$TC/gnohome}
pid=$(lsof -t -iTCP:27157 -sTCP:LISTEN 2>/dev/null || true)
[ -n "$pid" ] && kill "$pid" && sleep 2
P=gno.land/p/gnoradio; R=gno.land/r/gnoradio
paths=$P/text/v0,$P/svg/v0,$P/store/v0,$P/safe/v0,$P/blocks/v0,$P/role/v0,$R/data,$R/catalog/v1,$R/tickets/nft,$R/tickets/v1,$R/radio/v1,$R/home/v1,gno.land/r/sys/users
# The devseed realm (gitignored, generated by tools/dev/seedgen.py) loads the catalogue on a devnet only.
[ -d gno/r/gnoradio/devseed/v0 ] && paths=$paths,$R/devseed/v0
# Both owner addresses get GNOT (the second is the local Adena account).
nohup "$TC/gnodev" local -empty-blocks -no-watch \
  -node-rpc-listener 127.0.0.1:27157 -web-listener 127.0.0.1:8911 -chain-id dev \
  -extra-root ./gno -paths "$paths" -web-home /r/gnoradio/home/v1 \
  -add-account g1mpkp5lm8lwpm0pym4388836d009zfe4maxlqsq=1000000000000ugnot \
  -add-account g15wmukt79xymnnu6c4de32trnufudqum60yrxu8=1000000000000ugnot \
  > "${GNODEV_LOG:-/tmp/gnoradio-gnodev.log}" 2>&1 &
for _ in $(seq 60); do curl -s -o /dev/null http://127.0.0.1:27157/status && break; sleep 2; done
curl -s http://127.0.0.1:27157/status | grep -q latest_block_height && echo "devnet up: rpc 127.0.0.1:27157, gnoweb 127.0.0.1:8911" || { echo "gnodev did not start, see the log"; exit 1; }
